// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

declare module 'vue' {
    export interface GlobalComponents {
        Bar: typeof import('./components/Bar.vue')['default'];
        BookmarkBars: typeof import('./components/BookmarksBars.vue')['default'];
        Create: typeof import('./components/Create.vue')['default'];
        Edit: typeof import('./components/Edit.vue')['default'];
        Extension: typeof import('./components/Extension.vue')['default'];
        Modal: typeof import('./components/Modal.vue')['default'];
    }
}
